spring.application.name=delivery-chat

spring.datasource.url=jdbc:postgresql://localhost:5432/delivery_chat
spring.datasource.username=OWNER
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.exammple.delivery_chat.entity